# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4704009877ef3ed3eee8eddcbf5c90e076c9ae490b8bdf86b57359c08343ebf58049ae3221b5fb0f05a33c501b206816e4b4b2aa1ce8d5469609ed5d0ed7a286

test:
  secret_key_base: 1fd9769070c4d97b77fdb833b4274ca1ac8fee2c0ebf2329fc19906addde6cb77f87ca5c5149a7309ba1336e50f42340e074617b7dd6522f35c8900f5e4021c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
